<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CommonModels\CommonModels.csproj" />
      <ProjectReference Include="..\DBCore\DBCore.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ClosedXML" Version="0.105.0" />
      <PackageReference Include="EPPlus" Version="8.4.2" />
      <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="ReportGeneration\report_template.xlsx" />
      <EmbeddedResource Include="ReportGeneration\report_template.xlsx">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </EmbeddedResource>
    </ItemGroup>

</Project>
