<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-TechKasConnector-5f6ea53f-a5ce-475d-af91-87af1d89e525</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1"/>
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
        <PackageReference Include="NLog" Version="6.0.7" />
        <PackageReference Include="NLog.Web" Version="6.1.0" />
        <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>
</Project>
