<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CommonModels\CommonModels.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentNHibernate" Version="3.4.1" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="NHibernate" Version="5.6.0" />
      <PackageReference Include="Npgsql" Version="10.0.0-rc.1" />
    </ItemGroup>

    <ItemGroup>
      <None Update="settings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
