databaseConnectionString: "Server=localhost;Database=myDB;User Id=user;Password=pass;"
rabbitMQConnectionString: "amqp://localhost:5672"
techkasFilters:
  Common:
    include:
      "ИсточникОбращения":
        - "1761155"
        - "1761153"
        - "1761152"
        - "6753420"
        - "1761156"
        - "3010066"
        - "4521240"
        - "1768268"
        - "4081742"
        - "1761154"
    exclude:
      "ОбластьПоддержки":
        - "30262732"
      "Организация": 
        - "2070891"
  Beta:
    exclude: 
      